### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "safdar1111@yahoo.com",
    "password": "123"
}
###

### Signin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "safdar1111@yahoo.com",
  "password": "123"
}
###

### Get signin in user
GET http://localhost:3000/auth/whoami

### Signout user
POST http://localhost:3000/auth/signout

### Get user by Id
GET http://localhost:3000/auth/2

### Get user by email
GET http://localhost:3000/auth?email=safdar11@yahoo.com

### Delete user
DELETE http://localhost:3000/auth/11

### Update user
PATCH http://localhost:3000/auth/211
Content-Type: application/json

{
  "password": "2121"
}
###

### Set Cookie
GET http://localhost:3000/auth/colors/red

### Get Cookie
GET http://localhost:3000/auth/colors
