### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "safdar@yahoo.com",
    "password": "123"
}
###

### Get user by Id
GET http://localhost:3000/auth/12

### Get user by email
GET http://localhost:3000/auth?email=safdar11@yahoo.com

### Delete user
DELETE http://localhost:3000/auth/1

### Update user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "safdar111@yahoo.com"
}
###

